### ISSUE TITLE
Swamp is all slime blocks...

### ISSUE THREAD

**Issue by Jacob-Suldaan** [TheNimbleNinja/Project-Spelunca-Montis-Fabric#1]
Like the title says all grass blocks in the swamp are slime blocks?

https://gyazo.com/c1fbce415e6768dd8cb3d28f13e99014

**Comment by TheNimbleNinja** [comment]
um wat the heck
i have no idea wat is causing this but its free slime LUL

**Comment by TheNimbleNinja** [comment]
i figured out wat that was its a mod i added making a swamp biome have slime blocks its fine it doesnt hurt anything
