### ISSUE TITLE
Can't use or craft tools

### ISSUE THREAD

**Issue by missjess33** [TheNimbleNinja/Project-Spelunca-Montis-Fabric#2]
I would love to play this modpack, but I can't craft any tools, even using the crafting table, nor am I able to use tools to mine blocks or fight hostile mobs. I can only hit/mine with my bare hand or a stick for some reason... I tried deleting and re-creating a new world to see if it was just an issue with my first load, but the problem persisted. :/

**Comment by TheNimbleNinja** [comment]
u were probly using stone or wooden tools when that feature was disabled. in the next update there will be a guide on how to progress so dont worry too much :)
